FROM node:14-alpine

RUN mkdir -p /server/node_modules && chown -R node:node /server

WORKDIR /server

COPY ./server/package*.json ./

USER node

RUN npm install

COPY --chown=node:node . . 

EXPOSE 8081

CMD [ "node", "server.js" ]