FROM node:14-alpine

RUN apk update && \
    apk add git

EXPOSE 8080

RUN mkdir -p /client

WORKDIR /client

COPY ./client/package*.json ./

RUN npm cache clean --force && \
    npm install && \
    npm i -D es-dev-server

CMD [ "npm", "run", "serve" ]